// Generated by scripts/build-catalogue.mjs — do not edit by hand.
export const lookbook = [
  {
    "url": "/uploads/lookbook-1.webp",
    "caption": "Bangles by the hundred, Westlands"
  },
  {
    "url": "/uploads/lookbook-2.webp",
    "caption": "The cuff cabinet"
  },
  {
    "url": "/uploads/lookbook-3.webp",
    "caption": "The cuff table"
  },
  {
    "url": "/uploads/lookbook-4.webp",
    "caption": "Hammered brass, by the board"
  },
  {
    "url": "/uploads/lookbook-5.webp",
    "caption": "Flag bands, stacked"
  },
  {
    "url": "/uploads/lookbook-6.webp",
    "caption": "The long table"
  }
] as const;
